//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_SPLASH_H
#define METASPRITE_SPLASH_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define SPLASH_TILE_ORIGIN 0
#define SPLASH_TILE_W 8
#define SPLASH_TILE_H 8
#define SPLASH_WIDTH 160
#define SPLASH_HEIGHT 144
#define SPLASH_TILE_COUNT 165
#define SPLASH_PALETTE_COUNT 7
#define SPLASH_COLORS_PER_PALETTE 4
#define SPLASH_TOTAL_COLORS 28
#define SPLASH_MAP_ATTRIBUTES SPLASH_map_attributes
#define SPLASH_MAP_ATTRIBUTES_WIDTH 20
#define SPLASH_MAP_ATTRIBUTES_HEIGHT 18
#define SPLASH_MAP_ATTRIBUTES_PACKED_WIDTH 20
#define SPLASH_MAP_ATTRIBUTES_PACKED_HEIGHT 18

BANKREF_EXTERN(SPLASH)

extern const palette_color_t SPLASH_palettes[28];
extern const uint8_t SPLASH_tiles[2640];

extern const unsigned char SPLASH_map[360];
extern const unsigned char SPLASH_map_attributes[360];

#endif
